name: Android Release

on:
  push:
    branches:
      - main
      - feature/weather-status
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - uses: gradle/actions/setup-gradle@v4

      - uses: android-actions/setup-android@v4

      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > release.jks

      - name: Verify keystore
        run: |
          ls -lh release.jks
          keytool -list \
            -keystore release.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            -alias "${{ secrets.KEY_ALIAS }}"

      - name: Create keystore.properties
        run: |
          echo "storeFile=release.jks" > keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Build Release APK
        run: gradle :app:assembleRelease --stacktrace --no-daemon

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: DEACX Widget Latest
          files: app/build/outputs/apk/release/app-release.apk
          prerelease: true
